### ISSUE TITLE
Issue accessing index.php after login

### ISSUE THREAD

**Issue by ace2go** [austinkregel/php-login-advanced#1]
After I create an account, and then login via the credentials, it then redirects with the following statement : 
"
Forbidden

You don't have permission to access /index.php on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
"

Any idea what might cause this?

**Comment by austinkregel** [comment]
Were you trying to access my demo or were you doing this on your own server?

**Comment by ace2go** [comment]
on a web hosted server, which for additional info, I cannot enable cookies in the config.php, because when I do, I login and only get a blank screen

**Comment by austinkregel** [comment]
Cookies are enabled by default the only thing changing "COOKIE_DOMAIN" (Which is what I am assuming you're talking about) will do is limit the cookie to a specific domain. 
As far as the 403 error goes, did you do a fresh install? If so, double check the permissions of the files and make sure that the files have 644 or -rw-rw-r-- permissions and the folders have  775 permissions or drwxrwzr-x

**Comment by ace2go** [comment]
This was a fresh install, I set the files as you demonstrated, and still no go.  you can see what I mean @ itembundle.com

**Comment by austinkregel** [comment]
Is there an error_log file anywhere?

**Comment by ace2go** [comment]
[19-Mar-2015 14:33:13 America/New_York] PHP Notice:  Undefined index: HTTP_ACCEPT_LANGUAGE in /home/itempkqg/public_html/PHPLogin.php on line 56
[19-Mar-2015 16:49:58 America/New_York] PHP Parse error:  syntax error, unexpected '.' in /home/itempkqg/public_html/config/config.php on line 40

**Comment by austinkregel** [comment]
Okay, do you have an .htaccess file somewhere? (if you're using apache that is...)

**Comment by ace2go** [comment]
line 40 btw : define("COOKIE_DOMAIN", .itembundle.com); 
under the "views" folder htaccess as follows : 

<Files ~ "\.(htaccess|php)$">
order allow,deny
deny from all
</Files>

**Comment by austinkregel** [comment]
Okay, presently, try this `define("COOKIE_DOMAIN", "itembundle.com");`

**Comment by ace2go** [comment]
Cookies fixed!, but now there is no error log, and I am back to the cannot access index.php error

**Comment by ace2go** [comment]
Do you know what else could cause that permissions issue to index.php?  Edit : Just found out I get the same error no matter how I try to login, using different passwords, etc.  For some reason, after I register an account, and use the same password used for registering, I get this error.  Maybe something wonky going on with the way it is saving the password?

**Comment by austinkregel** [comment]
Are you able to access just an index.php page?
Does it have access to the database?
And have you tried devplanete's version?

**Comment by ace2go** [comment]
Just found out that it was a permissions issue that was being blocked by my domain hosting services :P

**Comment by austinkregel** [comment]
I figured it had to have been a permissions issue, just had no clue where. I'm really glad you were able to figure it out! ^.^
