### ISSUE TITLE
use png captcha

### ISSUE THREAD

**Issue by pippuccio76** [austinkregel/php-login-advanced#28]
Sorry for question , how can i use a simple png captcha ?

**Comment by austinkregel** [comment]
The short answer is No. It's only set up to use Google's recaptcha. Which is more dynamic and is javascript based.

**Comment by Wargog** [comment]
I wouldn't recommend using your own image captchas either way. Bots have gotten advanced enough to circumvent them anyhow, Recaptcha prevents a lot of that.

**Comment by austinkregel** [comment]
Closing to do inactivity.
