### ISSUE TITLE
Custom config location

### ISSUE THREAD

**Issue by Wargog** [austinkregel/php-login-advanced#8]
Would there be any way to make something that allows the user to set a custom location for the config, so if they would like to make a universal config for their project that includes the values for php-login as well as their scripts.

**Comment by austinkregel** [comment]
I'll definitely look into doing this, I might have to rewrite the way the project currently does the config but if it allows for more ease when making the config then I'm all for it!

**Comment by Wargog** [comment]
I only ask because my project makes the config through an installer, and it would be easier for me and I'm sure others to load the same values instead of rewriting them

**Comment by austinkregel** [comment]
I'll be getting to this at some point, I've been to busy lately to work on this system. I did manage to make a [flat-master ](http://php-login.austinkregel.com/flat-master/) version though. Next will be a config rewrite and a materialistic style. Then lastly I will do a very minimalistic (but still good looking design.

**Comment by austinkregel** [comment]
The master version of this repo does now support. I will have to update the Boostrap, Flat, and Materialistic versions accordingly.
